<?php

namespace Database\Seeders;

use App\Models\Institution;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class InstitutionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $institutions = [
            [
                'name' => 'Universitas Indonesia',
                'type' => 'Universitas',
                'address' => 'Kampus UI Depok',
                'city' => 'Depok',
                'province' => 'Jawa Barat',
                'postal_code' => '16424',
                'phone' => '021-7867222',
                'email' => 'humas-ui@ui.ac.id',
                'website' => 'https://www.ui.ac.id',
                'description' => 'Universitas Indonesia adalah perguruan tinggi negeri di Indonesia dengan program studi Ilmu Komunikasi yang unggul.',
                'joined_date' => Carbon::now()->subYears(5)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Gadjah Mada',
                'type' => 'Universitas',
                'address' => 'Bulaksumur, Caturtunggal',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55281',
                'phone' => '0274-588688',
                'email' => 'humas@ugm.ac.id',
                'website' => 'https://www.ugm.ac.id',
                'description' => 'Universitas Gadjah Mada memiliki Departemen Ilmu Komunikasi yang telah berdiri sejak lama dan menghasilkan lulusan berkualitas.',
                'joined_date' => Carbon::now()->subYears(4)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Padjadjaran',
                'type' => 'Universitas',
                'address' => 'Jl. Raya Bandung-Sumedang KM.21',
                'city' => 'Jatinangor',
                'province' => 'Jawa Barat',
                'postal_code' => '45363',
                'phone' => '022-7796200',
                'email' => 'info@unpad.ac.id',
                'website' => 'https://www.unpad.ac.id',
                'description' => 'Fakultas Ilmu Komunikasi Unpad adalah salah satu fakultas tertua dan terbaik di Indonesia.',
                'joined_date' => Carbon::now()->subYears(4)->subMonths(6)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Institut Teknologi Bandung',
                'type' => 'Institut',
                'address' => 'Jl. Ganesha No.10',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40132',
                'phone' => '022-2500935',
                'email' => 'itb@itb.ac.id',
                'website' => 'https://www.itb.ac.id',
                'description' => 'ITB memiliki program studi Seni Rupa dan Desain Komunikasi Visual yang berkualitas internasional.',
                'joined_date' => Carbon::now()->subYears(3)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Airlangga',
                'type' => 'Universitas',
                'address' => 'Jl. Airlangga No.4-6',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60286',
                'phone' => '031-5033869',
                'email' => 'humas@unair.ac.id',
                'website' => 'https://www.unair.ac.id',
                'description' => 'Universitas Airlangga memiliki program studi Ilmu Komunikasi dengan fokus pada komunikasi kesehatan.',
                'joined_date' => Carbon::now()->subYears(3)->subMonths(3)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Diponegoro',
                'type' => 'Universitas',
                'address' => 'Jl. Prof. Sudarto SH, Tembalang',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50275',
                'phone' => '024-7460024',
                'email' => 'humas@undip.ac.id',
                'website' => 'https://www.undip.ac.id',
                'description' => 'Undip memiliki Fakultas Ilmu Sosial dan Ilmu Politik dengan jurusan Ilmu Komunikasi yang berkembang pesat.',
                'joined_date' => Carbon::now()->subYears(3)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Brawijaya',
                'type' => 'Universitas',
                'address' => 'Jl. Veteran',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'postal_code' => '65145',
                'phone' => '0341-575777',
                'email' => 'humas@ub.ac.id',
                'website' => 'https://www.ub.ac.id',
                'description' => 'Universitas Brawijaya memiliki program studi Ilmu Komunikasi dengan keunggulan di bidang komunikasi bisnis.',
                'joined_date' => Carbon::now()->subYears(2)->subMonths(9)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Hasanuddin',
                'type' => 'Universitas',
                'address' => 'Jl. Perintis Kemerdekaan KM.10',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90245',
                'phone' => '0411-587219',
                'email' => 'humas@unhas.ac.id',
                'website' => 'https://www.unhas.ac.id',
                'description' => 'Unhas adalah perguruan tinggi terkemuka di Indonesia Timur dengan program studi komunikasi yang berkembang.',
                'joined_date' => Carbon::now()->subYears(2)->subMonths(6)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Sekolah Tinggi Ilmu Komunikasi - The London School of Public Relations',
                'type' => 'Sekolah Tinggi',
                'address' => 'Jl. K.H. Mas Mansyur Kav.35',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'phone' => '021-5747800',
                'email' => 'info@lspr.edu',
                'website' => 'https://www.lspr.edu',
                'description' => 'LSPR adalah sekolah tinggi komunikasi dengan fokus pada Public Relations dan komunikasi korporat.',
                'joined_date' => Carbon::now()->subYears(2)->subMonths(3)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Multimedia Nusantara',
                'type' => 'Universitas',
                'address' => 'Scientia Boulevard, Gading Serpong',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15811',
                'phone' => '021-54220808',
                'email' => 'info@umn.ac.id',
                'website' => 'https://www.umn.ac.id',
                'description' => 'UMN memiliki program studi Komunikasi Strategis dan Ilmu Jurnalistik dengan fasilitas multimedia terkini.',
                'joined_date' => Carbon::now()->subYears(2)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Pelita Harapan',
                'type' => 'Universitas',
                'address' => 'Jl. M.H. Thamrin Boulevard',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15811',
                'phone' => '021-5460901',
                'email' => 'info@uph.edu',
                'website' => 'https://www.uph.edu',
                'description' => 'UPH memiliki Fakultas Ilmu Komunikasi dengan program internasional dan fasilitas lengkap.',
                'joined_date' => Carbon::now()->subYears(1)->subMonths(9)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Bina Nusantara',
                'type' => 'Universitas',
                'address' => 'Jl. Kebon Jeruk Raya No.27',
                'city' => 'Jakarta Barat',
                'province' => 'DKI Jakarta',
                'postal_code' => '11530',
                'phone' => '021-5345830',
                'email' => 'info@binus.ac.id',
                'website' => 'https://www.binus.ac.id',
                'description' => 'Binus University memiliki program studi Marketing Communication dan Communication & Media Studies.',
                'joined_date' => Carbon::now()->subYears(1)->subMonths(6)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Institut Komunikasi dan Bisnis LSPR',
                'type' => 'Institut',
                'address' => 'Jl. K.H. Mas Mansyur Kav.35',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'phone' => '021-5747800',
                'email' => 'ikb@lspr.edu',
                'website' => 'https://www.lspr.edu',
                'description' => 'IKB LSPR fokus pada pendidikan Public Relations, Marketing Communication, dan Business Communication.',
                'joined_date' => Carbon::now()->subYears(1)->subMonths(3)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Politeknik Negeri Media Kreatif',
                'type' => 'Politeknik',
                'address' => 'Jl. Srengseng Sawah, Jagakarsa',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12640',
                'phone' => '021-7874335',
                'email' => 'info@polimedia.ac.id',
                'website' => 'https://www.polimedia.ac.id',
                'description' => 'Polimedia adalah politeknik yang fokus pada industri kreatif dan media komunikasi.',
                'joined_date' => Carbon::now()->subYears(1)->format('Y-m-d'),
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Mercu Buana',
                'type' => 'Universitas',
                'address' => 'Jl. Meruya Selatan, Kembangan',
                'city' => 'Jakarta Barat',
                'province' => 'DKI Jakarta',
                'postal_code' => '11650',
                'phone' => '021-5840816',
                'email' => 'info@mercubuana.ac.id',
                'website' => 'https://www.mercubuana.ac.id',
                'description' => 'UMB memiliki Fakultas Ilmu Komunikasi dengan program studi Broadcasting dan Jurnalistik.',
                'joined_date' => Carbon::now()->subMonths(9)->format('Y-m-d'),
                'is_active' => true,
            ],
        ];

        foreach ($institutions as $institution) {
            Institution::create($institution);
        }
    }
}
