<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Journal;
use Carbon\Carbon;

class JournalSeeder extends Seeder
{
    public function run(): void
    {
        $journals = [
            [
                'title' => 'Implementasi Machine Learning untuk Prediksi Cuaca di Indonesia',
                'authors' => 'Dr. Ahmad Fadli, M.Kom., Prof. Siti Nurhaliza, Ph.D., Dr. Budi Santoso, M.T.',
                'abstract' => 'Penelitian ini membahas implementasi algoritma machine learning untuk memprediksi cuaca di Indonesia. Menggunakan data historis dari BMKG selama 10 tahun terakhir, kami mengembangkan model prediksi yang dapat memberikan akurasi hingga 87%. Model yang dikembangkan menggunakan kombinasi Random Forest dan Neural Network untuk menghasilkan prediksi yang lebih akurat.',
                'volume' => '12',
                'issue' => '3',
                'year' => 2025,
                'pages' => '145-162',
                'doi' => '10.1234/jti.2025.12.3.145',
                'keywords' => 'Machine Learning, Prediksi Cuaca, Random Forest, Neural Network, BMKG',
                'published_date' => Carbon::create(2025, 9, 15),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Teknologi Informasi',
            ],
            [
                'title' => 'Analisis Keamanan Sistem Informasi Berbasis Cloud Computing',
                'authors' => 'Dr. Rina Wati, M.Sc., Ahmad Yani, S.Kom., M.T.',
                'abstract' => 'Makalah ini menganalisis berbagai aspek keamanan dalam sistem informasi berbasis cloud computing. Penelitian mencakup evaluasi terhadap berbagai protokol keamanan, enkripsi data, dan manajemen akses. Hasil penelitian menunjukkan bahwa implementasi multi-factor authentication dapat meningkatkan keamanan sistem hingga 95%.',
                'volume' => '11',
                'issue' => '2',
                'year' => 2025,
                'pages' => '78-94',
                'doi' => '10.1234/jsi.2025.11.2.78',
                'keywords' => 'Cloud Computing, Keamanan Sistem, Enkripsi, MFA, Cybersecurity',
                'published_date' => Carbon::create(2025, 6, 20),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Keamanan Siber',
            ],
            [
                'title' => 'Pengembangan Aplikasi Mobile untuk Monitoring Kesehatan Lansia',
                'authors' => 'Siti Rahmawati, S.Kom., M.Kom., Dr. Hendra Wijaya, Sp.PD',
                'abstract' => 'Aplikasi mobile yang dikembangkan dalam penelitian ini bertujuan untuk memudahkan monitoring kesehatan lansia secara real-time. Aplikasi terintegrasi dengan wearable devices untuk mengumpulkan data vital signs seperti tekanan darah, detak jantung, dan kadar gula darah. Hasil uji coba menunjukkan tingkat kepuasan pengguna mencapai 92%.',
                'volume' => '8',
                'issue' => '1',
                'year' => 2025,
                'pages' => '23-41',
                'doi' => '10.1234/jkm.2025.8.1.23',
                'keywords' => 'Mobile Health, Monitoring Kesehatan, Lansia, IoT, Wearable Device',
                'published_date' => Carbon::create(2025, 3, 10),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Kesehatan Digital',
            ],
            [
                'title' => 'Optimasi Algoritma Routing pada Jaringan Sensor Nirkabel',
                'authors' => 'Prof. Dr. Bambang Sutrisno, M.T., Andi Prasetyo, S.T., M.T.',
                'abstract' => 'Penelitian ini mengusulkan algoritma routing yang dioptimasi untuk jaringan sensor nirkabel (WSN) dengan tujuan meningkatkan efisiensi energi dan memperpanjang masa pakai jaringan. Algoritma yang dikembangkan menggunakan pendekatan clustering adaptif dan menunjukkan peningkatan lifetime jaringan hingga 40% dibandingkan algoritma konvensional.',
                'volume' => '15',
                'issue' => '4',
                'year' => 2024,
                'pages' => '201-218',
                'doi' => '10.1234/jjn.2024.15.4.201',
                'keywords' => 'WSN, Routing Algorithm, Energy Efficiency, Clustering, IoT',
                'published_date' => Carbon::create(2024, 11, 25),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Jaringan Komputer',
            ],
            [
                'title' => 'Implementasi Blockchain untuk Traceability Produk Pertanian',
                'authors' => 'Dr. Dewi Kartika, M.Sc., Ir. Supriyadi, M.Agr., Ahmad Zainudin, S.Kom.',
                'abstract' => 'Makalah ini membahas implementasi teknologi blockchain untuk meningkatkan traceability produk pertanian dari hulu ke hilir. Sistem yang dikembangkan memungkinkan konsumen untuk melacak asal-usul produk pertanian secara transparan dan akurat. Implementasi di 5 wilayah pilot menunjukkan peningkatan kepercayaan konsumen hingga 85%.',
                'volume' => '9',
                'issue' => '2',
                'year' => 2024,
                'pages' => '112-130',
                'doi' => '10.1234/jap.2024.9.2.112',
                'keywords' => 'Blockchain, Traceability, Pertanian, Supply Chain, Smart Contract',
                'published_date' => Carbon::create(2024, 8, 5),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Blockchain',
            ],
            [
                'title' => 'Analisis Sentimen Media Sosial Menggunakan Deep Learning',
                'authors' => 'Rina Susanti, S.Kom., M.T., Dr. Faisal Rahman, M.Kom.',
                'abstract' => 'Penelitian ini mengembangkan model analisis sentimen untuk media sosial menggunakan teknik deep learning, khususnya LSTM dan BERT. Model dilatih menggunakan dataset lebih dari 1 juta tweet dalam Bahasa Indonesia. Hasil evaluasi menunjukkan akurasi model mencapai 89% untuk klasifikasi sentimen positif, negatif, dan netral.',
                'volume' => '13',
                'issue' => '1',
                'year' => 2025,
                'pages' => '45-63',
                'doi' => '10.1234/jdl.2025.13.1.45',
                'keywords' => 'Sentiment Analysis, Deep Learning, LSTM, BERT, NLP, Social Media',
                'published_date' => Carbon::create(2025, 2, 14),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Artificial Intelligence',
            ],
            [
                'title' => 'Sistem Rekomendasi E-Learning Berbasis Collaborative Filtering',
                'authors' => 'Dr. Hadi Santoso, M.Pd., Nurul Hidayah, S.Kom., M.Kom.',
                'abstract' => 'Sistem rekomendasi yang dikembangkan dalam penelitian ini menggunakan metode collaborative filtering untuk memberikan rekomendasi konten pembelajaran yang dipersonalisasi untuk setiap pengguna e-learning. Sistem diuji pada platform dengan 5000 pengguna aktif dan menunjukkan peningkatan engagement rate sebesar 65%.',
                'volume' => '10',
                'issue' => '3',
                'year' => 2024,
                'pages' => '167-185',
                'doi' => '10.1234/jel.2024.10.3.167',
                'keywords' => 'E-Learning, Recommender System, Collaborative Filtering, Personalization',
                'published_date' => Carbon::create(2024, 10, 18),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Pendidikan',
            ],
            [
                'title' => 'Deteksi Dini Penyakit Tanaman Menggunakan Computer Vision',
                'authors' => 'Ir. Yusuf Habibi, M.Sc., Dr. Linda Wijaya, S.P., M.Si.',
                'abstract' => 'Penelitian ini mengembangkan sistem deteksi dini penyakit tanaman menggunakan teknik computer vision dan deep learning. Model CNN yang dikembangkan mampu mengidentifikasi 15 jenis penyakit tanaman dengan akurasi 93%. Aplikasi mobile yang dihasilkan dapat digunakan petani untuk diagnosis cepat di lapangan.',
                'volume' => '7',
                'issue' => '2',
                'year' => 2024,
                'pages' => '89-107',
                'doi' => '10.1234/jpt.2024.7.2.89',
                'keywords' => 'Computer Vision, Plant Disease, CNN, Deep Learning, Agriculture',
                'published_date' => Carbon::create(2024, 6, 30),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Pertanian Digital',
            ],
            [
                'title' => 'Pengembangan Smart City Platform untuk Manajemen Lalu Lintas',
                'authors' => 'Dr. Ir. Agus Setiawan, M.T., Ratna Sari, S.T., M.T., Dedi Kurniawan, S.Kom.',
                'abstract' => 'Platform smart city yang dikembangkan mengintegrasikan berbagai sensor dan kamera untuk monitoring lalu lintas real-time. Sistem menggunakan AI untuk memprediksi kemacetan dan memberikan rekomendasi rute alternatif. Implementasi di 3 kota besar menunjukkan pengurangan waktu perjalanan rata-rata hingga 25%.',
                'volume' => '14',
                'issue' => '2',
                'year' => 2025,
                'pages' => '134-156',
                'doi' => '10.1234/jsc.2025.14.2.134',
                'keywords' => 'Smart City, Traffic Management, IoT, AI, Urban Planning',
                'published_date' => Carbon::create(2025, 5, 22),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Smart City',
            ],
            [
                'title' => 'Keamanan Data pada Sistem Internet of Things (IoT)',
                'authors' => 'Prof. Dr. Muhammad Iqbal, M.T., Sari Wulandari, S.Kom., M.Kom.',
                'abstract' => 'Penelitian ini menganalisis berbagai aspek keamanan data pada sistem IoT dan mengusulkan framework keamanan yang komprehensif. Framework yang dikembangkan mencakup enkripsi end-to-end, autentikasi perangkat, dan monitoring anomali. Evaluasi menunjukkan framework dapat mendeteksi 96% serangan yang umum terjadi pada sistem IoT.',
                'volume' => '11',
                'issue' => '4',
                'year' => 2025,
                'pages' => '223-245',
                'doi' => '10.1234/jiot.2025.11.4.223',
                'keywords' => 'IoT Security, Data Protection, Encryption, Authentication, Anomaly Detection',
                'published_date' => Carbon::create(2025, 8, 12),
                'views' => rand(100, 500),
                'downloads' => rand(50, 200),
                'is_published' => true,
                'category' => 'Internet of Things',
            ],
        ];

        foreach ($journals as $journal) {
            Journal::create($journal);
        }

        $this->command->info('10 data jurnal dummy berhasil dibuat!');
    }
}
